{"Timestamp":"2024-06-01T22:45:51.0816388+07:00","Level":"Information","MessageTemplate":"============================================","Properties":{"SourceContext":"Initializor:","SrcContext":"   Initializor:    ","AccUSpace":"             "}}
{"Timestamp":"2024-06-01T22:45:51.1128673+07:00","Level":"Information","MessageTemplate":"Initializing GameServer build","Properties":{"SourceContext":"Initializor:","SrcContext":"   Initializor:    ","AccUSpace":"             "}}
{"Timestamp":"2024-06-01T22:45:51.1142817+07:00","Level":"Information","MessageTemplate":"New IDS","Properties":{"SourceContext":"Initializor:","SrcContext":"   Initializor:    ","AccUSpace":"             "}}
{"Timestamp":"2024-06-01T22:45:51.1154770+07:00","Level":"Information","MessageTemplate":"Latest S4","Properties":{"SourceContext":"Initializor:","SrcContext":"   Initializor:    ","AccUSpace":"             "}}
{"Timestamp":"2024-06-01T22:45:51.1168089+07:00","Level":"Information","MessageTemplate":"============================================","Properties":{"SourceContext":"Initializor:","SrcContext":"   Initializor:    ","AccUSpace":"             "}}
{"Timestamp":"2024-06-01T22:45:51.1180043+07:00","Level":"Information","MessageTemplate":"Initializing Database","Properties":{"SourceContext":"Initializor:","SrcContext":"   Initializor:    ","AccUSpace":"             "}}
{"Timestamp":"2024-06-01T22:45:51.1241373+07:00","Level":"Information","MessageTemplate":"Initializing...","Properties":{"SourceContext":"AuthDatabase","SrcContext":"   AuthDatabase    ","AccUSpace":"             "}}
{"Timestamp":"2024-06-01T22:45:53.5787107+07:00","Level":"Error","MessageTemplate":"MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No connection could be made because the target machine actively refused it 127.0.0.1:3306\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)\r\n   at MySql.Data.MySqlClient.NativeDriver.Open()\r\n---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): No connection could be made because the target machine actively refused it 127.0.0.1:3306\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)\r\n   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---\r\n\r\n   at MySql.Data.MySqlClient.NativeDriver.Open()\r\n   at MySql.Data.MySqlClient.Driver.Open()\r\n   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)\r\n   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()\r\n   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()\r\n   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()\r\n   at MySql.Data.MySqlClient.MySqlPool.GetConnection()\r\n   at MySql.Data.MySqlClient.MySqlConnection.Open()\r\n   at NeoNetsphere.AuthDatabase.Open() in D:\\Project\\S4League-Emu-1332-master\\src\\GameServer\\Program.cs:line 811\r\n   at NeoNetsphere.AuthDatabase.Initialize() in D:\\Project\\S4League-Emu-1332-master\\src\\GameServer\\Program.cs:line 761\r\n   at NeoNetsphere.Program.Main() in D:\\Project\\S4League-Emu-1332-master\\src\\GameServer\\Program.cs:line 163","Properties":{"SrcContext":"                   ","AccUSpace":"             "}}
